name: App Tests
on: [push]

jobs:
  nodejs-test:
    name: Run nodejs tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: lambda

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NodeJS dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint --fix --color fizzbuzz.js
