name: Terraform Apply
on:
  push:
    branches:
      - main
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - run: terraform init -backend=true

      - run: terraform validate -no-color

      # Checks that all Terraform configuration files adhere to a canonical format
      - run: terraform fmt -check

      - run: terraform plan

      # Apply infrastruture
      - name: Terraform Apply
        run: terraform apply -auto-approve
